export const po_dues_Data = [
  {
    dateRequested: "13-07-2024",
    rfpNumber: "RFP-PO-2024-25-201",
    vendorRegistration: "Pending",
    actions: "Register vendor",
  },
  {
    dateRequested: "14-07-2024",
    rfpNumber: "RFP-PO-2024-25-202",
    vendorRegistration: "Approved",
    actions: "Complete registration",
  },
  {
    dateRequested: "15-07-2024",
    rfpNumber: "RFP-PO-2024-25-203",
    vendorRegistration: "Rejected",
    actions: "Contact support",
  },
  {
    dateRequested: "16-07-2024",
    rfpNumber: "RFP-PO-2024-25-204",
    vendorRegistration: "Pending",
    actions: "Submit documents",
  },
  {
    dateRequested: "17-07-2024",
    rfpNumber: "RFP-PO-2024-25-205",
    vendorRegistration: "Approved",
    actions: "Schedule meeting",
  },
  {
    dateRequested: "18-07-2024",
    rfpNumber: "RFP-PO-2024-25-206",
    vendorRegistration: "Pending",
    actions: "Verify details",
  },
  {
    dateRequested: "19-07-2024",
    rfpNumber: "RFP-PO-2024-25-207",
    vendorRegistration: "Approved",
    actions: "Complete payment",
  },
  {
    dateRequested: "20-07-2024",
    rfpNumber: "RFP-PO-2024-25-208",
    vendorRegistration: "Rejected",
    actions: "Review rejection reasons",
  },
  {
    dateRequested: "21-07-2024",
    rfpNumber: "RFP-PO-2024-25-209",
    vendorRegistration: "Pending",
    actions: "Submit additional info",
  },
  {
    dateRequested: "22-07-2024",
    rfpNumber: "RFP-PO-2024-25-210",
    vendorRegistration: "Approved",
    actions: "Review documents",
  },
  {
    dateRequested: "23-07-2024",
    rfpNumber: "RFP-PO-2024-25-211",
    vendorRegistration: "Pending",
    actions: "Contact vendor",
  },
  {
    dateRequested: "24-07-2024",
    rfpNumber: "RFP-PO-2024-25-212",
    vendorRegistration: "Approved",
    actions: "Send confirmation",
  },
  {
    dateRequested: "25-07-2024",
    rfpNumber: "RFP-PO-2024-25-213",
    vendorRegistration: "Rejected",
    actions: "Reapply",
  },
  {
    dateRequested: "26-07-2024",
    rfpNumber: "RFP-PO-2024-25-214",
    vendorRegistration: "Pending",
    actions: "Await approval",
  },
  {
    dateRequested: "27-07-2024",
    rfpNumber: "RFP-PO-2024-25-215",
    vendorRegistration: "Approved",
    actions: "Schedule follow-up",
  },
  {
    dateRequested: "28-07-2024",
    rfpNumber: "RFP-PO-2024-25-216",
    vendorRegistration: "Pending",
    actions: "Submit final documents",
  },
  {
    dateRequested: "29-07-2024",
    rfpNumber: "RFP-PO-2024-25-217",
    vendorRegistration: "Approved",
    actions: "Send welcome package",
  },
  {
    dateRequested: "30-07-2024",
    rfpNumber: "RFP-PO-2024-25-218",
    vendorRegistration: "Rejected",
    actions: "Appeal decision",
  },
  {
    dateRequested: "31-07-2024",
    rfpNumber: "RFP-PO-2024-25-219",
    vendorRegistration: "Pending",
    actions: "Verify submission",
  },
  {
    dateRequested: "01-08-2024",
    rfpNumber: "RFP-PO-2024-25-220",
    vendorRegistration: "Approved",
    actions: "Update records",
  },
  {
    dateRequested: "02-08-2024",
    rfpNumber: "RFP-PO-2024-25-221",
    vendorRegistration: "Pending",
    actions: "Submit missing info",
  },
  {
    dateRequested: "03-08-2024",
    rfpNumber: "RFP-PO-2024-25-222",
    vendorRegistration: "Approved",
    actions: "Finalize registration",
  },
  {
    dateRequested: "04-08-2024",
    rfpNumber: "RFP-PO-2024-25-223",
    vendorRegistration: "Rejected",
    actions: "Reevaluate application",
  },
];

export const open_po_Data = [
  {
    poNumber: "PO001",
    rfpNumber: "RFP1001",
    grnStatus: "Pending",
    invoiceNumber: "INV1001",
  },
  {
    poNumber: "PO002",
    rfpNumber: "RFP1002",
    grnStatus: "Received",
    invoiceNumber: "INV1002",
  },
  {
    poNumber: "PO003",
    rfpNumber: "RFP1003",
    grnStatus: "Pending",
    invoiceNumber: "INV1003",
  },
  {
    poNumber: "PO004",
    rfpNumber: "RFP1004",
    grnStatus: "Received",
    invoiceNumber: "INV1004",
  },
  {
    poNumber: "PO005",
    rfpNumber: "RFP1005",
    grnStatus: "Pending",
    invoiceNumber: "INV1005",
  },
  {
    poNumber: "PO006",
    rfpNumber: "RFP1006",
    grnStatus: "Received",
    invoiceNumber: "INV1006",
  },
  {
    poNumber: "PO007",
    rfpNumber: "RFP1007",
    grnStatus: "Pending",
    invoiceNumber: "INV1007",
  },
  {
    poNumber: "PO008",
    rfpNumber: "RFP1008",
    grnStatus: "Received",
    invoiceNumber: "INV1008",
  },
  {
    poNumber: "PO009",
    rfpNumber: "RFP1009",
    grnStatus: "Pending",
    invoiceNumber: "INV1009",
  },
  {
    poNumber: "PO010",
    rfpNumber: "RFP1010",
    grnStatus: "Received",
    invoiceNumber: "INV1010",
  },
  {
    poNumber: "PO011",
    rfpNumber: "RFP1011",
    grnStatus: "Pending",
    invoiceNumber: "INV1011",
  },
  {
    poNumber: "PO012",
    rfpNumber: "RFP1012",
    grnStatus: "Received",
    invoiceNumber: "INV1012",
  },
  {
    poNumber: "PO013",
    rfpNumber: "RFP1013",
    grnStatus: "Pending",
    invoiceNumber: "INV1013",
  },
  {
    poNumber: "PO014",
    rfpNumber: "RFP1014",
    grnStatus: "Received",
    invoiceNumber: "INV1014",
  },
  {
    poNumber: "PO015",
    rfpNumber: "RFP1015",
    grnStatus: "Pending",
    invoiceNumber: "INV1015",
  },
  {
    poNumber: "PO016",
    rfpNumber: "RFP1016",
    grnStatus: "Received",
    invoiceNumber: "INV1016",
  },
  {
    poNumber: "PO017",
    rfpNumber: "RFP1017",
    grnStatus: "Pending",
    invoiceNumber: "INV1017",
  },
  {
    poNumber: "PO018",
    rfpNumber: "RFP1018",
    grnStatus: "Received",
    invoiceNumber: "INV1018",
  },
  {
    poNumber: "PO019",
    rfpNumber: "RFP1019",
    grnStatus: "Pending",
    invoiceNumber: "INV1019",
  },
  {
    poNumber: "PO020",
    rfpNumber: "RFP1020",
    grnStatus: "Received",
    invoiceNumber: "INV1020",
  },
];

export const grn_received_Data = [
  {
    poNumber: "PO101",
    rfpNumber: "RFP2001",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO102",
    rfpNumber: "RFP2002",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO103",
    rfpNumber: "RFP2003",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO104",
    rfpNumber: "RFP2004",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO105",
    rfpNumber: "RFP2005",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO106",
    rfpNumber: "RFP2006",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO107",
    rfpNumber: "RFP2007",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO108",
    rfpNumber: "RFP2008",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO109",
    rfpNumber: "RFP2009",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO110",
    rfpNumber: "RFP2010",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO111",
    rfpNumber: "RFP2011",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO112",
    rfpNumber: "RFP2012",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO113",
    rfpNumber: "RFP2013",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO114",
    rfpNumber: "RFP2014",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO115",
    rfpNumber: "RFP2015",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO116",
    rfpNumber: "RFP2016",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO117",
    rfpNumber: "RFP2017",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO118",
    rfpNumber: "RFP2018",
    grnStatus: "Completed",
  },
  {
    poNumber: "PO119",
    rfpNumber: "RFP2019",
    grnStatus: "Pending",
  },
  {
    poNumber: "PO120",
    rfpNumber: "RFP2020",
    grnStatus: "Completed",
  },
];
